spring:
    application:
        name: notification-service
    datasource:
        username: sa
        password: password
        url: jdbc:postgresql://localhost:5432/notification-service
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    kafka:
        bootstrap-servers: localhost:9092
        topics:
            partitions: 3
            notification:
                notification-send:
                    post-created: post-created-notification
                    post-liked: post-liked-notification
                    comment-liked: comment-liked-notification
    mail:
        host: smtp.gmail.com
        port: 587
        username: '${EMAIL_USER}'
        password: '${EMAIL_PASSWORD}'
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
server:
    port: 8400

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
springdoc:
    api-docs:
        enabled: true
