spring:
    main:
        web-application-type: reactive
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
server:
    port: 8765

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

jwt:
    validation:
        link: http://localhost:8000/api/v1/security/validate
    prefix: 'Bearer '

services:
    security-service: 'lb://SECURITY-SERVICE'
    user-service: 'lb://USER-SERVICE'
    post-service: 'lb://POST-SERVICE'
    follower-service: 'lb://FOLLOWER-SERVICE'

#http://localhost:8765/webjars/swagger-ui/index.html
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        url: http://localhost:8765/v3/api-docs
        urls:
            - name: security-service
              url: /security-service/api-docs
            - name: user-service
              url: /user-service/api-docs
            - name: post-service
              url: /post-service/api-docs
            - name: follower-service
              url: /follower-service/api-docs