spring:
    application:
        name: post-service
    datasource:
        username: sa
        password: password
        url: jdbc:postgresql://localhost:5432/post-service
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    kafka:
        bootstrap-servers: localhost:9092
        topics:
            partitions: 3
            notification:
                post: post-notification
                post-liked: post-liked-notification
                comment-liked: comment-liked-notification

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8200
springdoc:
    api-docs:
        enabled: true
    