spring:
    application:
        name: follower-service
    datasource:
        username: sa
        password: password
        url: jdbc:postgresql://localhost:5432/follower-service
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    kafka:
        bootstrap-servers: localhost:9092
        topics:
            partitions: 3
            notification:
                post: post-notification
                notification-send:
                    post-created: post-created-notification
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        user-service: user-service

server:
    port: 8300
springdoc:
    api-docs:
        enabled: true
        path: /api-docs