DROP TABLE IF EXISTS t_users CASCADE;

CREATE TABLE t_users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(100),
    name       VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    image_url  VARCHAR(500),
    birthday   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_t_users PRIMARY KEY (user_id)
);

ALTER TABLE t_users
    ADD CONSTRAINT uc_t_users_email UNIQUE (email);