DROP TABLE IF EXISTS t_users CASCADE;
DROP TABLE If EXISTS t_photos CASCADE;

CREATE TABLE t_users
(
    user_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email             VARCHAR(100),
    nickname          VARCHAR(100),
    name              VARCHAR(100),
    bio               VARCHAR(1000),
    location          VARCHAR(200),
    user_photo_id     UUID,
    birthday          TIMESTAMP WITHOUT TIME ZONE,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    is_public_account BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_t_users PRIMARY KEY (user_id)
);

CREATE TABLE t_photos
(
    id         UUID NOT NULL,
    image_url  VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    CONSTRAINT pk_t_photos PRIMARY KEY (id)
);

ALTER TABLE t_users
    ADD CONSTRAINT uc_t_users_email UNIQUE (email);

ALTER TABLE t_users
    ADD CONSTRAINT FK_T_USERS_ON_USER_PHOTO FOREIGN KEY (user_photo_id) REFERENCES t_photos (id);

ALTER TABLE t_photos
    ADD CONSTRAINT FK_T_PHOTOS_ON_USER FOREIGN KEY (user_id) REFERENCES t_users (user_id);