DROP TABLE IF EXISTS t_users CASCADE;
DROP TABLE If EXISTS t_photos CASCADE;

CREATE TABLE t_users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(100),
    name          VARCHAR(50),
    user_photo_id UUID,
    birthday      TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_t_users PRIMARY KEY (user_id)
);

CREATE TABLE t_photos
(
    id         UUID NOT NULL,
    image_url  VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    CONSTRAINT pk_t_photos PRIMARY KEY (id)
);

ALTER TABLE t_users
    ADD CONSTRAINT uc_t_users_email UNIQUE (email);

ALTER TABLE t_users
    ADD CONSTRAINT FK_T_USERS_ON_USER_PHOTO FOREIGN KEY (user_photo_id) REFERENCES photo (id);

ALTER TABLE t_photos
    ADD CONSTRAINT FK_T_PHOTOS_ON_USER FOREIGN KEY (user_id) REFERENCES t_users (user_id);